### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by chandryou** [statgarten/dockerImage#1]
Docker image versioning 및 기반이 되는 R version을 명시해주시면 좋겠습니다. 
@ChangwooLim

**Comment by ChangwooLim** [comment]
Docker Image Versioning 완료했습니다.
Push 시 v* 형태(예: v0.0.1, v0.1.2-rev5)로 tagging 하면 github action이 작동하며, 자동으로 lastest와 해당 태그를 부착합니다.

**Comment by ChangwooLim** [comment]
Now Specifying R Version at README.md, and dependency packages at each package repository(DESCRIPTION)
