### ISSUE TITLE
Amazon Machine Image(AMI) 면 충분

### ISSUE THREAD

**Issue by jinseob2kim** [statgarten/dockerImage#2]
Cloudformation까지는 필요없고, AMI면  충분합니다.

- https://docs.aws.amazon.com/ko_kr/AWSEC2/latest/UserGuide/AMIs.html

다른 분이 운영중인 rstudio/shiny 이미지입니다.https://www.louisaslett.com/RStudio_AMI/

**Comment by ChangwooLim** [comment]
AMI Completed
