### ISSUE TITLE
특정 Package 설치 문제

### ISSUE THREAD

**Issue by ChangwooLim** [statgarten/dockerImage#3]
- rstan 설치 오류
- apt-get install -y r-cran-rstan 로 해결
- -> library(rstan)으로는 불러와지나, statgarten 제대로 설치되지 않음.

**Comment by jinseob2kim** [comment]
rstan 이 필요한가요? 이거 베이지안통계때 쓰는 패키지입니다

**Comment by ChangwooLim** [comment]
stove 패카지에서 요구하고 있습니다. stove이슈에도 올려놨고 우회 방법으로 우선 넘어갔습니다.

**Comment by ChangwooLim** [comment]
stove 패카지에서 요구하고 있습니다. stove이슈에도 올려놨고 우회 방법으로 우선 넘어갔습니다.
